apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: src-pvc
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: src-pod 
spec:
  containers:
  - name: data-owner
    image: debian:11-slim
    command:
    - /bin/sh
    - -c
    - |
      while : ; do
        date | tee -a /data/date.txt
        sleep 1
      done
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: src-pvc
