builds:
- id: cbt-controller
  dir: .
  main: ./cmd/cbt-controller
  env:
  - CGO_ENABLED=0
- id: cbt-populator
  dir: .
  main: ./cmd/cbt-populator
  env:
  - CGO_ENABLED=0

defaultPlatforms:
- linux/amd64
- linux/arm64
