apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlite3
  namespace: snapshot-demo
  labels:
    app.kubernetes.io/name: sqlite3
spec:
  replicas: 1
  podManagementPolicy: Parallel
  serviceName: sqlite3
  selector:
    matchLabels:
      app.kubernetes.io/name: sqlite3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sqlite3
    spec:
      securityContext:
        fsGroup: 101 # gid=101(sqlite)
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
      - name: initdb
        image: keinos/sqlite3:3.40.0
        command:
        - sh
        - -c
        - |
          if [ ! -f /data/sqlite3/demo.db ]
          then
            echo "creating test DB"
            sqlite3 /data/sqlite3/demo.db <<HEREDOC
              create table demo(timestamp text, description text);
              insert into demo values(datetime("now"),"First sample data. Hoo");
              insert into demo values(datetime("now"),"Second sample data. Bar");
          HEREDOC
          fi
        volumeMounts:
        - name: sqlite3-data
          mountPath: /data/sqlite3
      containers:
      - name: sqlite3
        image: keinos/sqlite3:3.40.0
        command:
        - sh
        - -c
        - |
          sqlite3 /data/sqlite3/demo.db -header -column 'SELECT rowid, * FROM demo;'
          sleep 4h
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 2Gi
        volumeMounts:
        - name: sqlite3-data
          mountPath: /data/sqlite3
  volumeClaimTemplates:
  - metadata:
      name: sqlite3-data
      labels:
        app.kubernetes.io/name: sqlite3
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-sc
