apiVersion: v1
kind: ServiceAccount
metadata:
  name: cbt-populator
  namespace: cbt-populator
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cbt-populator
  namespace: cbt-populator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cbt-populator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cbt-populator
    spec:
      serviceAccount: cbt-populator
      containers:
      - name: cbt-populator
        image: ko://github.com/ihcsim/cbt-populator/cmd/cbt-controller
        imagePullPolicy: IfNotPresent
        args:
        - --populator-image
        - ko://github.com/ihcsim/cbt-populator/cmd/cbt-populator
        - --listen-addr
        - :8080
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
