kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cbt-populator
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "patch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontents"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cbt.storage.k8s.io"]
  resources: ["changedblockranges"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cbt-populator
subjects:
- kind: ServiceAccount
  name: cbt-populator
  namespace: cbt-populator
- kind: ServiceAccount
  name: default
  namespace: cbt-populator
roleRef:
  kind: ClusterRole
  name: cbt-populator
  apiGroup: rbac.authorization.k8s.io
