on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52
        args: --timeout 5m
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: checkout code
      uses: actions/checkout@v3
    - name: test
      run: make test
  push:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      repository-projects: write
    needs:
    - lint
    - test
    steps:
    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: checkout code
      uses: actions/checkout@v3
    - name: set up ko
      uses: ko-build/setup-ko@v0.6
    - run: make push
